title: Suu Nhuy
author: giahuy
email: giahuy2201@outlook.com
description: >-
  Curiosity takes me places
baseurl: "/blog" # subpath
url: "https://www.suunhuy.com"
github_username:  giahuy2201

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-toc

sass:
  quiet_deps: true

toc:
  max_level: 1 # default: 6